dist: trusty
language: php

php:
  - 7.1
  - 7.2

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpstan analyse --level=7 ./ -c ./phpstan.neon
  - ./vendor/bin/phpunit --coverage-clover coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

## Cache composer
cache:
  directories:
  - $HOME/.cache/composer